#!/usr/bin/bash
# Autostart script ran before starting wm

# Power management
# doas /usr/bin/tlp bat &
# doas /usr/bin/powertop --auto-tune &

doas /usr/bin/light -I &
xset r rate 300 35 &

xrdb ~/.Xresources &
# redshift &
~/.fehbg &
# picom -b &

# Screenlock script
/home/four/.local/bin/tools/xidlehook.sh &

# Launch dwm status bar
/bedrock/cross/bin/dwmblocks &
