#!/usr/bin/bash
# Autostart script ran before starting wm

# Power management
sudo tlp bat &
sudo powertop --auto-tune &

sudo light -I &
xset r rate 300 35 &

xrdb ~/.Xresources &
redshift &
~/.fehbg &
picom -b &

# Screenlock script
/home/four/.local/bin/tools/xidlehook.sh &

# Launch dwm status bar
dwmblocks &
